name: Generate changelog
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Target release version (semver, git tag, branch or commit)'
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
      - name: "Checkout Grafana repo"
        uses: "actions/checkout@v4"
        with:
          sparse-checkout: |
            .github/workflows
            CHANGELOG.md
          fetch-depth: 0
          fetch-tags: true
      - name: "Generate changelog"
        id: changelog
        uses: ./.github/workflows/actions/changelog
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          target: v${{ inputs.version }}
          output_file: changelog_items.md
      - name: "Patch CHANGELOG.md"
        run: |
          # Replace text between the delimiters with new changelog_items.md content
          sed -i '/${{ inputs.version }} START/,/${{ inputs.version }} END/{
            //!d
            e cat changelog_items.md
          }' CHANGELOG.md
          git diff CHANGELOG.md
      - name: "Draft Github Release"
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          cat changelog_items.md
          # skip for now
          # gh release create --draft ${{ inputs.version }} --notes-file _changelog.md
