name: Generate changelog
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Target release version (semver, git tag, branch or commit)'
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
      - name: "Checkout Grafana repo"
        uses: "actions/checkout@v4"
        with:
          sparse-checkout: |
            .github/workflows
            CHANGELOG.md
          fetch-depth: 0
          fetch-tags: true
      - name: "Generate changelog"
        id: changelog
        uses: ./.github/workflows/actions/changelog
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          target: v${{ inputs.version }}
          output_file: changelog_items.md
      - name: "Patch CHANGELOG.md"
        run: |
          # Prepare CHANGELOG.md content with version delimiters
          (
            echo
            echo "# ${{ inputs.version}} $(date '+%F')"
            echo
            cat changelog_items.md
          ) > CHANGELOG.part

          cat CHANGELOG.part

          # Check if a version exists in the changelog
          if grep -q "<!-- ${{ inputs.version}} START" CHANGELOG.md ; then
            # Replace the content between START and END delimiters
            echo "Version ${{ inputs.version }} is found in the CHANGELOG.md, patching contents..."
            sed -i -e '/${{ inputs.version }} START/,/${{ inputs.version }} END/{//!d;}' \
                   -e '/${{ inputs.version }} START/r changelog_items.md' CHANGELOG.md
          else
            # Prepend changelog part to the main changelog file
            echo "Version ${{ inputs.version }} not found in the CHANGELOG.md"
            (
              echo "<!-- ${{ inputs.version }} START -->"
              cat CHANGELOG.part
              echo "<!-- ${{ inputs.version }} END -->"
              cat CHANGELOG.md
            ) > CHANGELOG.tmp
            mv CHANGELOG.tmp CHANGELOG.md
          fi

          git diff CHANGELOG.md
      - name: "Draft Github Release"
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          cat changelog_items.md
          # skip for now
          # gh release create --draft ${{ inputs.version }} --notes-file _changelog.md
