name: Feature toggles CI

on:
  pull_request:
    paths:
      - 'pkg/services/featuremgmt/toggles_gen_test.go'
      - 'pkg/services/featuremgmt/registry.go'
      - 'docs/sources/setup-grafana/configure-grafana/feature-toggles/index.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run feature toggle tests
        run: go test -v -run TestFeatureToggleFiles ./pkg/services/featuremgmt/
