name: End-to-end tests for cloud plugins

on:
  pull_request:
    paths:
      - pkg/tsdb/azuremonitor/**
      - public/app/plugins/datasource/azuremonitor/**
      - e2e-playwright/cloud-plugins-suite/azure-monitor.spec.ts
  push:
    branches:
      - main
      - release-*.*.*
    paths:
      - pkg/tsdb/azuremonitor/**
      - public/app/plugins/datasource/azuremonitor/**
      - e2e-playwright/cloud-plugins-suite/azure-monitor.spec.ts

permissions: {}

jobs:
  pull-docker-image:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/shared-workflows/actions/login-to-gar@login-to-gar-v0.4.0
        id: login-to-gar
        with:
          registry: "us-docker.pkg.dev"
          environment: "dev"
          delete_credentials_file: true
      - id: pull-docker-image
        run: |
          docker pull us-docker.pkg.dev/grafanalabs-dev/docker-oss-plugin-partnerships-dev/e2e-playwright:latest
  run-azure-monitor-e2e:
    name: E2E tests for azure monitor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    container:
      image: us-docker.pkg.dev/grafanalabs-dev/docker-oss-plugin-partnerships-dev/e2e-playwright:latest
    needs: pull-docker-image
    steps:
      - id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          repo_secrets: |
            AZURE_SP_APP_ID=cpp-azure-resourcemanager-credentials:application_id
            AZURE_SP_PASSWORD=cpp-azure-resourcemanager-credentials:application_secret
            AZURE_TENANT=cpp-azure-resourcemanager-credentials:tenant_id

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build Grafana
        uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e
        with:
          verb: run
          args: go run ./pkg/build/cmd artifacts -a targz:grafana:linux/amd64 --grafana-dir="${PWD}" > out.txt

      - name: Deploy resources
        run: |
          ./cpp-e2e/scripts/ci-run.sh azure ${{ github.ref_name }} deploy
      - name: Run E2E tests
        run: yarn e2e:playwright --grep @cloud-plugins

      - name: Destroy resources
        run: |
          ./cpp-e2e/scripts/ci-run.sh azure ${{ github.ref_name }} destroy
