# Owned by grafana-delivery-squad
# Intended to be dropped into the base repo Ex: grafana/grafana
name: Dispatch check for patch conflicts
run-name: dispatch-check-patch-conflicts-${{ github.base_ref }}-${{ github.head_ref }}
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "main"
      - "v*.*.*"
      - "release-*"

# Since this is run on a pull request, we want to apply the patches intended for the
# target branch onto the source branch, to verify compatibility before merging.
jobs:
  dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          # App needs Actions: Read/Write for the grafana/security-patch-actions repo
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
      - name: "Dispatch job"
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          env:
            SRC_REPO: ${{ github.repository }}
            SRC_REF: ${{ github.head_ref }}
            SRC_MERGE_SHA: ${{ github.sha }}
            SRC_PR_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
            PATCH_REPO: ${{ github.repository }}-security-patches
            PATCH_REF: ${{ github.base_ref }}
            TRIGGERING_GITHUB_HANDLE: ${{ github.event.sender.login }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
                owner: 'grafana',
                repo: 'security-patch-actions',
                workflow_id: 'test-patches-event.yml',
                ref: 'main',
                inputs: {
                  src_repo: process.env.SRC_REPO,
                  src_ref: process.env.SRC_REF,
                  src_merge_sha: process.env.SRC_MERGE_SHA,
                  src_pr_commit_sha: process.env.SRC_PR_COMMIT_SHA,
                  patch_repo: process.env.PATCH_REPO,
                  patch_ref: process.env.PATCH_REF,
                  triggering_github_handle: process.env.TRIGGERING_GITHUB_HANDLE
                }
            })
